name: 🛠️ Development Task
description: Create a development task for features, fixes, refactoring, or chores
title: '[TASK] '
labels: ['task']
projects: ['email-assistant']
assignees: []

body:
  - type: dropdown
    id: task-type
    attributes:
      label: 📋 Task Type
      description: What type of development task is this?
      options:
        - 🚀 Feature - New functionality or enhancement
        - 🐛 Fix - Bug fix or issue resolution
        - 🔨 Refactor - Code improvement without changing functionality
        - 🧹 Chore - Maintenance, dependencies, or tooling
        - 📚 Documentation - Documentation updates or improvements
        - 🧪 Testing - Adding or improving tests
        - 🔧 Configuration - Configuration changes or improvements
      default: 0
    validations:
      required: true

  - type: dropdown
    id: module
    attributes:
      label: 📦 Module
      description: Which module/service does this task affect?
      options:
        - 📧 Email Service - SMTP/IMAP, sending, receiving
        - 🤖 AI Service - AI providers, function calls, content analysis
        - 👥 User Management - Authentication, user data, permissions
        - ⏰ Scheduler Service - Cron jobs, reminders, task scheduling
        - 🖥️ Frontend - Vue.js components, UI, user interface
        - 🔧 System Services - Health, monitoring, performance
        - 📊 Data Management - Context, cache, storage
        - 🔐 Security - Authentication, authorization, data protection
        - 📝 Configuration - Config management, environment variables
        - 🏗️ Infrastructure - Build, deployment, CI/CD
        - 📖 Documentation - API docs, user guides, README
        - 🧪 Testing - Unit tests, integration tests, e2e tests
        - 🔄 Other - Please specify in description
      default: 0
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: 🎯 Priority
      description: How urgent is this task?
      options:
        - 🔴 Critical - Blocking production or major functionality
        - 🟠 High - Important for next release
        - 🟡 Medium - Should be done soon
        - 🟢 Low - Nice to have, can be delayed
      default: 2
    validations:
      required: true

  - type: dropdown
    id: estimated-time
    attributes:
      label: ⏱️ Estimated Time
      description: How long do you estimate this task will take?
      options:
        - 1h - Quick fix or small change
        - 4h - Half day task
        - 1d - Full day task
        - 2d - Two day task
        - 1w - Week-long task
        - 2w+ - Large task (consider breaking down)
      default: 2
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: Detailed description of the task
      placeholder: |
        Describe what needs to be done:
        - Current situation
        - What needs to be changed/added
        - Expected outcome
        - Any constraints or considerations
    validations:
      required: false

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: ✅ Acceptance Criteria
      description: Clear criteria for when this task is complete
      placeholder: |
        - [ ] Criteria 1
        - [ ] Criteria 2
        - [ ] Criteria 3
        - [ ] Tests are updated/added
        - [ ] Documentation is updated (if needed)
    validations:
      required: false

  - type: textarea
    id: technical-notes
    attributes:
      label: 🔧 Technical Notes
      description: Technical details, approach, or implementation notes
      placeholder: |
        - Files to modify: 
        - Approach:
        - Dependencies:
        - Testing considerations:
        - Rollback plan (if needed):
    validations:
      required: false

  - type: textarea
    id: related-issues
    attributes:
      label: 🔗 Related Issues
      description: Link to related issues, PRs, or discussions
      placeholder: |
        - Related to #123
        - Blocks #456
        - Depends on #789
        - See discussion: #abc
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: 📋 Pre-work Checklist
      description: Complete before starting work
      options:
        - label: I have searched for existing similar tasks
        - label: I have considered the impact on other modules
        - label: I have estimated the effort accurately
        - label: I have identified any dependencies
        - label: I understand the acceptance criteria
